config/routes.rb
DayzBarters::Application.routes.draw do
  root 'trades#index'

  resources :offers

  resources :locations

  resources :trades

  resources :loots do
    collection { post :import }
  end

  resources :users

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :purchaser, foreign_key: "purchaser_id", class_name: "User"
  belongs_to :trade, foreign_key: "trade_id", class_name: "Trade"

  serialize :offered
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @offer }
      else
        format.html { render action: 'new' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:trade_id, :offered, :purchaser_id, :threat_level, :accepted)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trade_id %><br>
    <%= f.number_field :trade_id %>
  </div>
  <div class="field">
    <%= f.label :offered %><br>
    <%= f.text_area :offered %>
  </div>
  <div class="field">
    <%= f.label :purchaser_id %><br>
    <%= f.number_field :purchaser_id %>
  </div>
  <div class="field">
    <%= f.label :threat_level %><br>
    <%= f.number_field :threat_level %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br>
    <%= f.check_box :accepted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <thead>
    <tr>
      <th>Trade</th>
      <th>Offered</th>
      <th>Purchaser</th>
      <th>Threat level</th>
      <th>Accepted</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.trade_id %></td>
        <td><%= offer.offered %></td>
        <td><%= offer.purchaser_id %></td>
        <td><%= offer.threat_level %></td>
        <td><%= offer.accepted %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trade:</strong>
  <%= @offer.trade_id %>
</p>

<p>
  <strong>Offered:</strong>
  <%= @offer.offered %>
</p>

<p>
  <strong>Purchaser:</strong>
  <%= @offer.purchaser_id %>
</p>

<p>
  <strong>Threat level:</strong>
  <%= @offer.threat_level %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @offer.accepted %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>