config/routes.rb
DayzBarters::Application.routes.draw do
  root 'trades#index'

  resources :offers

  resources :locations

  resources :trades

  resources :loots do
    collection { post :import }
  end

  resources :users

end

app/views/layouts/_alerts.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= alert %>
  </div>
<% elsif flash[:notice] %>
  <div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= notice %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small><br />
    DayZ Barters &copy; 2014
  </small>
  <nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "DayZ Barters", root_path, id: "logo", class: "home-logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to trades_path do %>
	    <span class="fa fa-tag"></span>
            &nbsp;Trades<% end %>
	  </li>
	  <li><%= link_to users_path do %>
	    <span class="fa fa-user"></span>
            &nbsp;Users<% end %>
          </li>
	  <li><%= link_to loots_path do %>
	    <span class="fa fa-briefcase"></span>
            &nbsp;Loot<% end %>
          </li>
          <li><%= link_to locations_path do %>
	    <span class="fa fa-globe"></span>
            &nbsp;Locations<% end %>
          </li>
          <li><%= link_to offers_path do %>
	    <span class="fa fa-ticket"></span>
            &nbsp;My Offers<% end %>
          </li>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_new_form.html.erb
<div class="row">
  <div class="span6 col-centered">
    <div class="well">

      <%= yield %>

  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DayzBarters</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag 'http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
  <%= render 'layouts/alerts' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>